### ISSUE TITLE
Continous play

### ISSUE THREAD

**Issue by rome3ro** [SuperrSonic/WiiMC-SS#1]
Hello SuperrSonic, I was wondering if it is possible to decrease the time that is elapsed when is playing the next video when you have enabled the option of continuous play, this is because I'm using a m3u8 url to stream it and the video needs to be continuously playing without delay, I will really appreciate your help and by the way congrats for you effort on this new version of wiimc!

**Comment by SuperrSonic** [comment]
This is a personal/private build for testing things, it's not the kind of thing people should be using.

The main purpose was to fix the pixel aspect ratio in 4:3 mode and remove deflicker filter.
There's also [this](https://github.com/SuperrSonic/WiiMC-SSLC) with the idea that removing the picture viewer frees up more mem1, which might help stability and maybe even performance.

About your problem:
I'll try to help but this project is pretty much finished. Is the delay the buffering text? Try setting cache fill to lowest, if you do what you say on videos stored locally they play instantly, streaming them is just too slow. Even so setting the cache to 10% should only delay for a few seconds.
If I were you I would download the stream and play from an SD card.
