### ISSUE TITLE
Wiimc

### ISSUE THREAD

**Issue by Kokokool** [SuperrSonic/WiiMC-SS#2]
Hi.
Since Wiimc official development has stopped and there plenty of new enhancements going around, i want to ask something that has been annoying me in every version:

1.- is there a way to enable movie navigation such as, FF, Rewind, jump to, etc, **while** streaming from a movie url? for instance, archive.org.

2.- Every .ts or m3u8 (even SD or HD) livestreams drops back to the menu in 10 seconds of transmission, is there a way to avoid this? i mean, to let the system automatically buffers and let the video runs continously? i know that SD.

Would like to know if you had had the chance to modify this aspect.

**Comment by SuperrSonic** [comment]
Sorry just spotted this, this isn't the current WiiMC-SS repo it's https://github.com/SuperrSonic/WiiMC-SSLC

I am aware of the issue with http streaming dropping out, it seems that if WiiMC is not frequently downloading then the connection will stop and play what it has left from the memory cache.

I added a setting you could try (by editing settings.xml) it changes the cache filling from 8MB to 2MB, which is enough for streaming, just avoid pausing the stream. The streams I've tested run all the way through.
